# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mendel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_from', models.IntegerField()),
                ('position_to', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of_type', models.CharField(choices=[('CSV', 'csv'), ('TXT', 'txt')], max_length=2)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mendel.Category')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mendel.Content')),
            ],
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='is_stopword',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='review',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mendel.Keyword'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='content',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mendel.Document'),
        ),
        migrations.AddField(
            model_name='content',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mendel.Keyword'),
        ),
    ]
