# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mendel', '0002_auto_20160510_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='of_type',
            field=models.CharField(choices=[('CSV', 'csv'), ('TXT', 'txt')], max_length=10),
        ),
    ]
