# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mendel', '0003_auto_20160519_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 27, 20, 11, 52, 520000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 27, 20, 12, 4, 380000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 27, 20, 12, 13, 211000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 27, 20, 12, 15, 568000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 27, 20, 12, 16, 992000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 27, 20, 12, 18, 331000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 27, 20, 12, 20, 132000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 27, 20, 12, 21, 663000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 27, 20, 12, 23, 280000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 27, 20, 12, 24, 892000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('context', 'keyword', 'category', 'user', 'status')]),
        ),
    ]
