# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mendel', '0003_auto_20160510_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], max_length=20),
        ),
    ]
