# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mendel', '0004_auto_20160527_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mendel.Context'),
        ),
    ]
