# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mendel', '0005_auto_20160609_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
