# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mendel', '0006_category_description'),
        ('mendel', '0005_auto_20160603_1833'),
    ]

    operations = [
    ]
