# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mendel', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='architizer_id',
            field=models.IntegerField(null=True, verbose_name='Architizer ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='of_type',
            field=models.CharField(choices=[('S', 'Product Search'), ('R', 'Product Response')], max_length=10, verbose_name='Type'),
        ),
    ]
