# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mendel', '0009_auto_20160623_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='keyword_given',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_given', to='mendel.Keyword'),
        ),
    ]
