branch-defaults:
  deploy:
    environment: architizer-mendel
    group_suffix: null
  master:
    environment: django-env
    group_suffix: null
global:
  application_name: architizer-mendel-prod
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-east-1
  profile: null
  sc: git
