branch-defaults:
  master:
    environment: architizer-mendel-prod
    group_suffix: null
  elastic-beanstalk:
    environment: architizer-mendel-stag
    group_suffix: null

global:
  application_name: architizer-mendel
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-east-1
  profile: null
  sc: git
